#Examen

In [44]:
import numpy as np
from math import sqrt
class formulas(): #Crea la clase principal

    def __init__(self, lado):
      self.lado = lado

class triangulo(formulas): #Clase heredada
    def __init__(self, lado):
        self.lado = lado

    def area_triangulo(self): #Hace una definición del área del triángulo
        area = (self.lado**2 * sqrt(3)) / 4 #Fórmula del área
        print(f"El area es de {area}")

    def perimetro_triangulo(self): #Hace una definición del perímetro del triángulo
        perimetro = 3 * self.lado #Fórmula del perímetro
        print(f"El perimetro es de {perimetro}")

class matriz(formulas):
    def __init__(self, M_matriz):
        self.M_matriz = M_matriz
        M = np.array(M_matriz).reshape(4,4) #Convierte la lista en una matriz 4x4
        print(f"La matriz es {M}")  #Imprime la matriz

class determinante(formulas):
    def __init__(self, M_matriz):
        M_matriz = M_matriz
        M = np.array(M_matriz).reshape(4,4) #Convierte la lista en una matriz 4x4
        Det = np.linalg.det(M) #Crea la determinante de la matriz
        print(f"La determinante de la matriz es {Det}") #Imprime la determinante de la matriz

In [45]:
triangulo1 = triangulo(6)
triangulo1.area_triangulo()
triangulo1.perimetro_triangulo()

El area es de 15.588457268119894
El perimetro es de 18


In [46]:
matriz([2, 4, 14, 15, 8, 7, 20, 22, 4, 2, 6, 7, 5, 8, 2, 4])

La matriz es [[ 2  4 14 15]
 [ 8  7 20 22]
 [ 4  2  6  7]
 [ 5  8  2  4]]


In [47]:
determinante([2, 4, 14, 15, 8, 7, 20, 22, 4, 2, 6, 7, 5, 8, 2, 4])

La determinante de la matriz es -147.9999999999998
